name: Send

on:
  - workflow_dispatch

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{steps.nvm.outputs.NODE_VERSION }}
      - name: Setup yarn cache
        id: yarncache
        run: echo ::set-output name=dir::$(yarn cache dir)
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarncache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Restore sent.json
        id: restore-sent
        uses: actions/cache@v2
        with:
          path: sent.json
          key: sent-${{ github.run_id }}
          restore-keys: sent-
      - name: Send
        env:
          DRY_RUN: ${{ secrets.DRY_RUN }}
          EMAIL_FROM: "${{ secrets.EMAIL_FROM }}"
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          SEND: ${{ secrets.SEND }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
        run: yarn send
